//! Standalone integration tests that self-provision their infrastructure.
//!
//! The TLS tests start a TLS-enabled `redis-server` with self-signed certs
//! generated by `redis-server-wrapper`, the same mechanism the cluster suite
//! uses in CI. No external endpoint or env var is required, so these tests run
//! in the normal pass when a TLS feature is enabled.
//!
//! TLS coverage requires either the `tls-rustls` or `tls-native-tls` feature.
//! The standalone integration job runs `--all-features`, exercising both:
//!
//! ```bash
//! cargo test -p redis-tower --test test_infrastructure --features tls-rustls
//! cargo test -p redis-tower --test test_infrastructure --features tls-native-tls
//! ```
//!
//! Cluster and sentinel integration tests live in the dedicated
//! `redis-tower-cluster` and `redis-tower-sentinel` crates.

// ---------------------------------------------------------------------------
// TLS tests (#153, #473)
//
// A single TLS server is shared across the TLS tests via a OnceCell. It is
// reachable only over its TLS port; certificates are self-signed, so the
// client trusts them via `danger_accept_invalid_certs`/`_hostnames`.
// ---------------------------------------------------------------------------

#[cfg(any(feature = "tls-rustls", feature = "tls-native-tls"))]
mod tls {
    use bytes::Bytes;
    use redis_server_wrapper::{RedisServer, RedisServerHandle};
    use redis_tower::RedisConnection;
    use redis_tower::commands::*;
    use tokio::sync::OnceCell;

    // Dedicated TLS port for this fixture; isolated from the shared 6399
    // default instance and the LFU fixture on 6388.
    const TLS_PORT: u16 = 6387;

    static TLS_SERVER: OnceCell<Option<RedisServerHandle>> = OnceCell::const_new();

    /// Start a TLS-enabled redis-server with generated certs. Returns `None` if
    /// certs cannot be generated or redis-server lacks TLS support.
    async fn ensure_tls_server() -> Option<&'static RedisServerHandle> {
        TLS_SERVER
            .get_or_init(|| async {
                let certs_dir =
                    std::path::PathBuf::from("/tmp/redis-tower-tls-infrastructure/certs");
                let certs = match redis_server_wrapper::tls::generate_test_certs(&certs_dir) {
                    Ok(c) => c,
                    Err(e) => {
                        eprintln!("skipping TLS tests: failed to generate certs: {e}");
                        return None;
                    }
                };

                // `port 0` disables the plaintext listener so the server is
                // reachable only over TLS, proving the client speaks TLS.
                match RedisServer::new()
                    .port(0)
                    .tls_port(TLS_PORT)
                    .tls_cert_file(&certs.cert_file)
                    .tls_key_file(&certs.key_file)
                    .tls_ca_cert_file(&certs.ca_cert_file)
                    .tls_auth_clients(false)
                    .start()
                    .await
                {
                    Ok(handle) => Some(handle),
                    Err(e) => {
                        eprintln!("skipping TLS tests: failed to start TLS server: {e}");
                        None
                    }
                }
            })
            .await
            .as_ref()
    }

    fn tls_addr() -> String {
        format!("127.0.0.1:{TLS_PORT}")
    }

    #[cfg(feature = "tls-rustls")]
    fn rustls_config() -> redis_tower_core::tls::TlsConfig {
        redis_tower_core::tls::TlsConfig::default_rustls()
            .danger_accept_invalid_certs(true)
            .danger_accept_invalid_hostnames(true)
    }

    #[cfg(feature = "tls-native-tls")]
    fn native_tls_config() -> redis_tower_core::tls::TlsConfig {
        redis_tower_core::tls::TlsConfig::default_native_tls()
            .danger_accept_invalid_certs(true)
            .danger_accept_invalid_hostnames(true)
    }

    // -- rustls backend --

    #[cfg(feature = "tls-rustls")]
    #[tokio::test]
    async fn tls_rustls_connect_and_ping() {
        let Some(_server) = ensure_tls_server().await else {
            eprintln!("skipping: redis-server not compiled with TLS support");
            return;
        };
        let mut conn = RedisConnection::connect_tls(&tls_addr(), "localhost", &rustls_config())
            .await
            .expect("rustls TLS connect should succeed");
        let pong = conn.execute(Ping::new()).await.unwrap();
        assert_eq!(pong, "PONG");
    }

    #[cfg(feature = "tls-rustls")]
    #[tokio::test]
    async fn tls_rustls_set_get_roundtrip() {
        let Some(_server) = ensure_tls_server().await else {
            eprintln!("skipping: redis-server not compiled with TLS support");
            return;
        };
        let mut conn = RedisConnection::connect_tls(&tls_addr(), "localhost", &rustls_config())
            .await
            .expect("rustls TLS connect should succeed");
        let key = "tls_test:rustls:key";
        conn.execute(Set::new(key, "value")).await.unwrap();
        let val = conn.execute(Get::new(key)).await.unwrap();
        assert_eq!(val, Some(Bytes::from("value")));
        conn.execute(Del::new(key)).await.unwrap();
    }

    // -- native-tls backend --

    #[cfg(feature = "tls-native-tls")]
    #[tokio::test]
    async fn tls_native_tls_connect_and_ping() {
        let Some(_server) = ensure_tls_server().await else {
            eprintln!("skipping: redis-server not compiled with TLS support");
            return;
        };
        let mut conn = RedisConnection::connect_tls(&tls_addr(), "localhost", &native_tls_config())
            .await
            .expect("native-tls TLS connect should succeed");
        let pong = conn.execute(Ping::new()).await.unwrap();
        assert_eq!(pong, "PONG");
    }

    #[cfg(feature = "tls-native-tls")]
    #[tokio::test]
    async fn tls_native_tls_set_get_roundtrip() {
        let Some(_server) = ensure_tls_server().await else {
            eprintln!("skipping: redis-server not compiled with TLS support");
            return;
        };
        let mut conn = RedisConnection::connect_tls(&tls_addr(), "localhost", &native_tls_config())
            .await
            .expect("native-tls TLS connect should succeed");
        let key = "tls_test:native:key";
        conn.execute(Set::new(key, "value")).await.unwrap();
        let val = conn.execute(Get::new(key)).await.unwrap();
        assert_eq!(val, Some(Bytes::from("value")));
        conn.execute(Del::new(key)).await.unwrap();
    }
}
