//! Redis Streams commands (Redis 5.0+)
//!
//! Streams are an append-only log data structure that allows producers to add
//! messages and consumers to read them. They support consumer groups for distributed
//! processing and automatic message delivery guarantees.

use crate::codec::Frame;
use crate::commands::Command;
use crate::types::RedisError;
use bytes::Bytes;
use std::collections::HashMap;

/// XADD command - Append a new entry to a stream
///
/// Appends the specified stream entry to the stream at the specified key. If the key does not exist,
/// it is created. An entry is composed of a set of field-value pairs. The entry ID is automatically
/// generated by default (format: "timestamp-sequence"), or can be explicitly specified.
///
/// # Request
/// - `key`: The stream key
/// - `id` (optional): Explicit entry ID (format: "timestamp-sequence", default: auto-generated "*")
/// - `fields`: One or more field-value pairs for the entry
/// - `maxlen` (optional): Cap stream to approximately N entries (~)
/// - `maxlen_exact` (optional): Cap stream to exactly N entries
/// - `nomkstream` (optional): Don't create stream if it doesn't exist (Redis 6.2+)
///
/// # Response
/// Returns `String` - The ID of the added entry (e.g., "1526919030474-0")
///
/// # Redis Version
/// Available since Redis 5.0.0. NOMKSTREAM option available since Redis 6.2.0.
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XAdd;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Add with auto-generated ID
/// let cmd = XAdd::new("sensor-data")
///     .field("temperature", "25.5")
///     .field("humidity", "60");
/// let entry_id = client.call(cmd).await?;
/// println!("Added entry: {}", entry_id);
///
/// // Add with specific ID
/// let cmd = XAdd::new("events")
///     .id("1526919030474-0")
///     .field("type", "user-login")
///     .field("user", "alice");
/// client.call(cmd).await?;
///
/// // Add with MAXLEN to cap stream size
/// let cmd = XAdd::new("logs")
///     .maxlen(1000)
///     .field("level", "info")
///     .field("message", "Server started");
/// client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XAdd {
    pub(crate) key: String,
    pub(crate) id: Option<String>,
    pub(crate) fields: Vec<(String, String)>,
    pub(crate) maxlen: Option<i64>,
    pub(crate) maxlen_approx: bool,
    pub(crate) nomkstream: bool,
}

impl XAdd {
    /// Create a new XADD command (ID will be auto-generated)
    pub fn new(key: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            id: None,
            fields: Vec::new(),
            maxlen: None,
            maxlen_approx: false,
            nomkstream: false,
        }
    }

    /// Set a specific stream entry ID (format: "timestamp-sequence")
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.id = Some(id.into());
        self
    }

    /// Add a field-value pair to the stream entry
    pub fn field(mut self, field: impl Into<String>, value: impl Into<String>) -> Self {
        self.fields.push((field.into(), value.into()));
        self
    }

    /// Limit stream to approximately N entries (uses ~ for approximate trimming)
    pub fn maxlen(mut self, count: i64) -> Self {
        self.maxlen = Some(count);
        self.maxlen_approx = true;
        self
    }

    /// Limit stream to exactly N entries (exact trimming, slower)
    pub fn maxlen_exact(mut self, count: i64) -> Self {
        self.maxlen = Some(count);
        self.maxlen_approx = false;
        self
    }

    /// Don't create stream if it doesn't exist (Redis 6.2+)
    pub fn nomkstream(mut self) -> Self {
        self.nomkstream = true;
        self
    }
}

impl Command for XAdd {
    type Response = String;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XADD"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ];

        if self.nomkstream {
            args.push(Frame::BulkString(Some(Bytes::from("NOMKSTREAM"))));
        }

        if let Some(maxlen) = self.maxlen {
            args.push(Frame::BulkString(Some(Bytes::from("MAXLEN"))));
            if self.maxlen_approx {
                args.push(Frame::BulkString(Some(Bytes::from("~"))));
            }
            args.push(Frame::BulkString(Some(Bytes::from(maxlen.to_string()))));
        }

        // ID or * for auto-generation
        if let Some(id) = &self.id {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        } else {
            args.push(Frame::BulkString(Some(Bytes::from("*"))));
        }

        // Field-value pairs
        for (field, value) in &self.fields {
            args.push(Frame::BulkString(Some(Bytes::from(field.clone()))));
            args.push(Frame::BulkString(Some(Bytes::from(value.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::BulkString(Some(data)) => Ok(String::from_utf8_lossy(&data).into_owned()),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XREAD command - Read data from one or more streams
///
/// Read data from one or more streams, only returning entries with an ID greater than the last received ID.
/// This command can block waiting for new data (with BLOCK option) or return immediately with available data.
///
/// # Request
/// - `count` (optional): Maximum number of entries to return per stream
/// - `block` (optional): Block for up to N milliseconds waiting for data (0 = block forever)
/// - `streams`: One or more (stream_key, last_id) pairs
///   - Use "0-0" to read from the beginning
///   - Use "$" to read only new entries
///
/// # Response
/// Returns `HashMap<String, Vec<StreamEntry>>` - Map of stream keys to their entries.
/// Returns empty map if no data available (or None when blocking times out).
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XRead;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Read all entries from stream
/// let cmd = XRead::new().stream("mystream", "0-0");
/// let data = client.call(cmd).await?;
///
/// // Read only new entries (block for 5 seconds)
/// let cmd = XRead::new()
///     .block(5000)
///     .stream("events", "$");
/// let data = client.call(cmd).await?;
///
/// // Read from multiple streams with count limit
/// let cmd = XRead::new()
///     .count(10)
///     .stream("stream1", "0-0")
///     .stream("stream2", "0-0");
/// let data = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XRead {
    pub(crate) count: Option<i64>,
    pub(crate) block: Option<i64>,
    pub(crate) streams: Vec<(String, String)>, // (key, id)
}

impl XRead {
    /// Create a new XREAD command
    pub fn new() -> Self {
        Self {
            count: None,
            block: None,
            streams: Vec::new(),
        }
    }

    /// Limit number of entries returned per stream
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }

    /// Block for up to N milliseconds waiting for new entries (0 = forever)
    pub fn block(mut self, milliseconds: i64) -> Self {
        self.block = Some(milliseconds);
        self
    }

    /// Add a stream to read from with starting ID
    /// Use "0-0" for all entries, "$" for only new entries
    pub fn stream(mut self, key: impl Into<String>, id: impl Into<String>) -> Self {
        self.streams.push((key.into(), id.into()));
        self
    }
}

impl Default for XRead {
    fn default() -> Self {
        Self::new()
    }
}

impl Command for XRead {
    type Response = Vec<StreamEntries>;

    fn to_frame(&self) -> Frame {
        let mut args = vec![Frame::BulkString(Some(Bytes::from("XREAD")))];

        if let Some(count) = self.count {
            args.push(Frame::BulkString(Some(Bytes::from("COUNT"))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
        }

        if let Some(block) = self.block {
            args.push(Frame::BulkString(Some(Bytes::from("BLOCK"))));
            args.push(Frame::BulkString(Some(Bytes::from(block.to_string()))));
        }

        args.push(Frame::BulkString(Some(Bytes::from("STREAMS"))));

        // First all keys, then all IDs
        for (key, _) in &self.streams {
            args.push(Frame::BulkString(Some(Bytes::from(key.clone()))));
        }
        for (_, id) in &self.streams {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Array(streams) => {
                let mut result = Vec::new();
                for stream in streams {
                    if let Frame::Array(pair) = stream {
                        if pair.len() == 2 {
                            let key = match &pair[0] {
                                Frame::BulkString(Some(k)) => {
                                    String::from_utf8_lossy(k).into_owned()
                                }
                                _ => return Err(RedisError::UnexpectedResponse),
                            };

                            let entries = parse_stream_entries(&pair[1])?;
                            result.push(StreamEntries { key, entries });
                        }
                    }
                }
                Ok(result)
            }
            Frame::Null => Ok(Vec::new()),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XRANGE command - Return a range of entries from a stream
///
/// Returns the stream entries matching a given range of IDs. The range is specified by a minimum
/// and a maximum ID. All the entries having an ID between the two specified IDs will be returned.
///
/// # Request
/// - `key`: The stream key
/// - `start`: Minimum entry ID (use "-" for the minimum ID in the stream)
/// - `end`: Maximum entry ID (use "+" for the maximum ID in the stream)
/// - `count` (optional): Limit number of entries returned
///
/// # Response
/// Returns `Vec<StreamEntry>` - Stream entries in the specified range, ordered by ID.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XRange;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Get all entries
/// let cmd = XRange::new("mystream", "-", "+");
/// let entries = client.call(cmd).await?;
///
/// // Get entries in specific ID range
/// let cmd = XRange::new("mystream", "1526985054069-0", "1526985055069-0");
/// let entries = client.call(cmd).await?;
///
/// // Get first 10 entries
/// let cmd = XRange::new("mystream", "-", "+").count(10);
/// let entries = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XRange {
    pub(crate) key: String,
    pub(crate) start: String,
    pub(crate) end: String,
    pub(crate) count: Option<i64>,
}

impl XRange {
    /// Create a new XRANGE command
    /// Use "-" for minimum ID, "+" for maximum ID
    pub fn new(key: impl Into<String>, start: impl Into<String>, end: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            start: start.into(),
            end: end.into(),
            count: None,
        }
    }

    /// Limit number of entries returned
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }
}

impl Command for XRange {
    type Response = Vec<StreamEntry>;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XRANGE"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.start.clone()))),
            Frame::BulkString(Some(Bytes::from(self.end.clone()))),
        ];

        if let Some(count) = self.count {
            args.push(Frame::BulkString(Some(Bytes::from("COUNT"))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        parse_stream_entries(&frame)
    }
}

/// XREVRANGE command - Return a range of entries from a stream in reverse order
///
/// This command is exactly like XRANGE, but with the IDs reported in reverse order, from the greater ID
/// to the smaller ID. It's useful to retrieve the latest items in a stream.
///
/// # Request
/// - `key`: The stream key
/// - `end`: Maximum entry ID (use "+" for the maximum ID in the stream)
/// - `start`: Minimum entry ID (use "-" for the minimum ID in the stream)
/// - `count` (optional): Limit number of entries returned
///
/// # Response
/// Returns `Vec<StreamEntry>` - Stream entries in the specified range, ordered from highest to lowest ID.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XRevRange;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Get last 10 entries (most recent first)
/// let cmd = XRevRange::new("mystream", "+", "-").count(10);
/// let entries = client.call(cmd).await?;
/// println!("Got {} recent entries", entries.len());
///
/// // Get all entries in reverse order
/// let cmd = XRevRange::new("mystream", "+", "-");
/// let entries = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XRevRange {
    pub(crate) key: String,
    pub(crate) end: String,
    pub(crate) start: String,
    pub(crate) count: Option<i64>,
}

impl XRevRange {
    /// Create a new XREVRANGE command
    /// Note: end comes before start (reversed)
    pub fn new(key: impl Into<String>, end: impl Into<String>, start: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            end: end.into(),
            start: start.into(),
            count: None,
        }
    }

    /// Limit number of entries returned
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }
}

impl Command for XRevRange {
    type Response = Vec<StreamEntry>;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XREVRANGE"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.end.clone()))),
            Frame::BulkString(Some(Bytes::from(self.start.clone()))),
        ];

        if let Some(count) = self.count {
            args.push(Frame::BulkString(Some(Bytes::from("COUNT"))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        parse_stream_entries(&frame)
    }
}

/// XLEN command - Returns the number of entries inside a stream
///
/// Returns the number of entries inside a stream. If the specified key does not exist, the command
/// returns zero, as if the stream was empty.
///
/// # Request
/// - `key`: The stream key
///
/// # Response
/// Returns `i64` - The number of entries in the stream, or 0 if the key does not exist.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XLen;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// let cmd = XLen::new("mystream");
/// let count = client.call(cmd).await?;
/// println!("Stream has {} entries", count);
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XLen {
    pub(crate) key: String,
}

impl XLen {
    /// Create a new XLEN command
    pub fn new(key: impl Into<String>) -> Self {
        Self { key: key.into() }
    }
}

impl Command for XLen {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XLEN"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XDEL command - Removes the specified entries from a stream
///
/// Removes the specified entries from the stream stored at key, and returns the number of entries
/// deleted, that may be different from the number of IDs passed if certain IDs do not exist.
///
/// # Request
/// - `key`: The stream key
/// - `ids`: One or more entry IDs to delete
///
/// # Response
/// Returns `i64` - The number of entries actually deleted.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XDel;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// let cmd = XDel::new("mystream")
///     .id("1526919030474-0")
///     .id("1526919030474-1");
/// let deleted = client.call(cmd).await?;
/// println!("Deleted {} entries", deleted);
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XDel {
    pub(crate) key: String,
    pub(crate) ids: Vec<String>,
}

impl XDel {
    /// Create a new XDEL command
    pub fn new(key: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            ids: Vec::new(),
        }
    }

    /// Add an ID to delete
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.ids.push(id.into());
        self
    }
}

impl Command for XDel {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XDEL"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ];

        for id in &self.ids {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XTRIM command - Trims the stream to a specified length
///
/// Trims the stream by evicting older entries (entries with lower IDs) if needed. The command can
/// trim to an approximate length (faster) or exact length.
///
/// # Request
/// - `key`: The stream key
/// - `maxlen` (optional): Trim to approximately N entries (~)
/// - `maxlen_exact` (optional): Trim to exactly N entries
///
/// # Response
/// Returns `i64` - The number of entries deleted.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XTrim;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Trim to approximately 1000 entries (faster)
/// let cmd = XTrim::new("mystream").maxlen(1000);
/// let deleted = client.call(cmd).await?;
///
/// // Trim to exactly 1000 entries
/// let cmd = XTrim::new("mystream").maxlen_exact(1000);
/// let deleted = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XTrim {
    pub(crate) key: String,
    pub(crate) maxlen: Option<i64>,
    pub(crate) maxlen_approx: bool,
}

impl XTrim {
    /// Create a new XTRIM command
    pub fn new(key: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            maxlen: None,
            maxlen_approx: false,
        }
    }

    /// Trim to approximately N entries (faster)
    pub fn maxlen(mut self, count: i64) -> Self {
        self.maxlen = Some(count);
        self.maxlen_approx = true;
        self
    }

    /// Trim to exactly N entries (slower)
    pub fn maxlen_exact(mut self, count: i64) -> Self {
        self.maxlen = Some(count);
        self.maxlen_approx = false;
        self
    }
}

impl Command for XTrim {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XTRIM"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ];

        if let Some(maxlen) = self.maxlen {
            args.push(Frame::BulkString(Some(Bytes::from("MAXLEN"))));
            if self.maxlen_approx {
                args.push(Frame::BulkString(Some(Bytes::from("~"))));
            }
            args.push(Frame::BulkString(Some(Bytes::from(maxlen.to_string()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XGROUP CREATE command - Create a consumer group
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XGroupCreate;
/// // Create group starting from beginning
/// let cmd = XGroupCreate::new("mystream", "mygroup", "0");
///
/// // Create group for new entries only
/// let cmd = XGroupCreate::new("mystream", "mygroup", "$");
///
/// // Create group and stream if it doesn't exist
/// let cmd = XGroupCreate::new("mystream", "mygroup", "0").mkstream();
/// ```
#[derive(Debug, Clone)]
pub struct XGroupCreate {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) id: String,
    pub(crate) mkstream: bool,
}

impl XGroupCreate {
    /// Create a new XGROUP CREATE command
    pub fn new(key: impl Into<String>, group: impl Into<String>, id: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            id: id.into(),
            mkstream: false,
        }
    }

    /// Create the stream if it doesn't exist
    pub fn mkstream(mut self) -> Self {
        self.mkstream = true;
        self
    }
}

impl Command for XGroupCreate {
    type Response = ();

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XGROUP"))),
            Frame::BulkString(Some(Bytes::from("CREATE"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.id.clone()))),
        ];

        if self.mkstream {
            args.push(Frame::BulkString(Some(Bytes::from("MKSTREAM"))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::SimpleString(_) => Ok(()),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XGROUP DESTROY command - Destroy a consumer group
#[derive(Debug, Clone)]
pub struct XGroupDestroy {
    pub(crate) key: String,
    pub(crate) group: String,
}

impl XGroupDestroy {
    /// Create a new XGROUP DESTROY command
    pub fn new(key: impl Into<String>, group: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
        }
    }
}

impl Command for XGroupDestroy {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XGROUP"))),
            Frame::BulkString(Some(Bytes::from("DESTROY"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XGROUP CREATECONSUMER command - Create a consumer in a consumer group (Redis 6.2+)
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XGroupCreateConsumer;
/// let cmd = XGroupCreateConsumer::new("mystream", "mygroup", "consumer1");
/// ```
#[derive(Debug, Clone)]
pub struct XGroupCreateConsumer {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) consumer: String,
}

impl XGroupCreateConsumer {
    /// Create a new XGROUP CREATECONSUMER command
    pub fn new(
        key: impl Into<String>,
        group: impl Into<String>,
        consumer: impl Into<String>,
    ) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            consumer: consumer.into(),
        }
    }
}

impl Command for XGroupCreateConsumer {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XGROUP"))),
            Frame::BulkString(Some(Bytes::from("CREATECONSUMER"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.consumer.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XGROUP DELCONSUMER command - Delete a consumer from a consumer group
///
/// Warning: Any pending messages for this consumer will become unclaimable.
/// It's recommended to claim or acknowledge all pending messages before deletion.
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XGroupDelConsumer;
/// let cmd = XGroupDelConsumer::new("mystream", "mygroup", "consumer1");
/// ```
#[derive(Debug, Clone)]
pub struct XGroupDelConsumer {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) consumer: String,
}

impl XGroupDelConsumer {
    /// Create a new XGROUP DELCONSUMER command
    pub fn new(
        key: impl Into<String>,
        group: impl Into<String>,
        consumer: impl Into<String>,
    ) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            consumer: consumer.into(),
        }
    }
}

impl Command for XGroupDelConsumer {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XGROUP"))),
            Frame::BulkString(Some(Bytes::from("DELCONSUMER"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.consumer.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XGROUP SETID command - Set the last delivered ID for a consumer group
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XGroupSetId;
/// // Set to reprocess all messages
/// let cmd = XGroupSetId::new("mystream", "mygroup", "0");
///
/// // Set to latest message
/// let cmd = XGroupSetId::new("mystream", "mygroup", "$");
///
/// // Set with entries_read for lag tracking (Redis 7.0+)
/// let cmd = XGroupSetId::new("mystream", "mygroup", "1234-0")
///     .entries_read(1000);
/// ```
#[derive(Debug, Clone)]
pub struct XGroupSetId {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) id: String,
    pub(crate) entries_read: Option<i64>,
}

impl XGroupSetId {
    /// Create a new XGROUP SETID command
    pub fn new(key: impl Into<String>, group: impl Into<String>, id: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            id: id.into(),
            entries_read: None,
        }
    }

    /// Set the entries_read count for lag tracking (Redis 7.0+)
    pub fn entries_read(mut self, count: i64) -> Self {
        self.entries_read = Some(count);
        self
    }
}

impl Command for XGroupSetId {
    type Response = String;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XGROUP"))),
            Frame::BulkString(Some(Bytes::from("SETID"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.id.clone()))),
        ];

        if let Some(count) = self.entries_read {
            args.push(Frame::BulkString(Some(Bytes::from("ENTRIESREAD"))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::SimpleString(s) => Ok(String::from_utf8_lossy(&s).to_string()),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XREADGROUP command - Read data from a stream via a consumer group
///
/// This command is a special version of XREAD with support for consumer groups. It reads entries from
/// streams and delivers them to consumers in the specified group. Using ">" as the ID means to receive
/// only new messages never delivered to other consumers.
///
/// # Request
/// - `group`: The consumer group name
/// - `consumer`: The consumer name
/// - `count` (optional): Maximum number of entries to return per stream
/// - `block` (optional): Block for up to N milliseconds waiting for data
/// - `streams`: One or more (stream_key, last_id) pairs
///   - Use ">" to receive only new/undelivered messages
///
/// # Response
/// Returns `HashMap<String, Vec<StreamEntry>>` - Map of stream keys to their entries.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XReadGroup;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Read new messages as consumer
/// let cmd = XReadGroup::new("mygroup", "consumer1")
///     .stream("mystream", ">");
/// let data = client.call(cmd).await?;
///
/// // With blocking and count
/// let cmd = XReadGroup::new("mygroup", "consumer1")
///     .block(5000)
///     .count(10)
///     .stream("mystream", ">");
/// let data = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XReadGroup {
    pub(crate) group: String,
    pub(crate) consumer: String,
    pub(crate) count: Option<i64>,
    pub(crate) block: Option<i64>,
    pub(crate) noack: bool,
    pub(crate) streams: Vec<(String, String)>,
}

impl XReadGroup {
    /// Create a new XREADGROUP command
    pub fn new(group: impl Into<String>, consumer: impl Into<String>) -> Self {
        Self {
            group: group.into(),
            consumer: consumer.into(),
            count: None,
            block: None,
            noack: false,
            streams: Vec::new(),
        }
    }

    /// Limit number of entries
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }

    /// Block for up to N milliseconds
    pub fn block(mut self, milliseconds: i64) -> Self {
        self.block = Some(milliseconds);
        self
    }

    /// Don't auto-acknowledge messages
    pub fn noack(mut self) -> Self {
        self.noack = true;
        self
    }

    /// Add a stream to read from
    /// Use ">" for new messages not yet delivered to any consumer
    pub fn stream(mut self, key: impl Into<String>, id: impl Into<String>) -> Self {
        self.streams.push((key.into(), id.into()));
        self
    }
}

impl Command for XReadGroup {
    type Response = Vec<StreamEntries>;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XREADGROUP"))),
            Frame::BulkString(Some(Bytes::from("GROUP"))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.consumer.clone()))),
        ];

        if let Some(count) = self.count {
            args.push(Frame::BulkString(Some(Bytes::from("COUNT"))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
        }

        if let Some(block) = self.block {
            args.push(Frame::BulkString(Some(Bytes::from("BLOCK"))));
            args.push(Frame::BulkString(Some(Bytes::from(block.to_string()))));
        }

        if self.noack {
            args.push(Frame::BulkString(Some(Bytes::from("NOACK"))));
        }

        args.push(Frame::BulkString(Some(Bytes::from("STREAMS"))));

        for (key, _) in &self.streams {
            args.push(Frame::BulkString(Some(Bytes::from(key.clone()))));
        }
        for (_, id) in &self.streams {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        XRead::parse_response(frame)
    }
}

/// XACK command - Marks a pending message as correctly processed
///
/// The XACK command removes one or multiple messages from the Pending Entries List (PEL) of a
/// stream consumer group. A message is pending when it was delivered to a consumer but not yet
/// acknowledged as processed.
///
/// # Request
/// - `key`: The stream key
/// - `group`: The consumer group name
/// - `ids`: One or more entry IDs to acknowledge
///
/// # Response
/// Returns `i64` - The number of messages successfully acknowledged.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XAck;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// let cmd = XAck::new("mystream", "mygroup")
///     .id("1526919030474-0")
///     .id("1526919030474-1");
/// let acked = client.call(cmd).await?;
/// println!("Acknowledged {} messages", acked);
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XAck {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) ids: Vec<String>,
}

impl XAck {
    /// Create a new XACK command
    pub fn new(key: impl Into<String>, group: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            ids: Vec::new(),
        }
    }

    /// Add an ID to acknowledge
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.ids.push(id.into());
        self
    }
}

impl Command for XAck {
    type Response = i64;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XACK"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
        ];

        for id in &self.ids {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Integer(n) => Ok(n),
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// XPENDING command - Inspect the list of pending messages in a consumer group
///
/// Returns information about pending messages in a consumer group. Pending messages are those that
/// have been delivered to consumers but not yet acknowledged with XACK.
///
/// # Request
/// - `key`: The stream key
/// - `group`: The consumer group name
/// - `start`, `end`, `count` (optional): Get detailed list of pending messages in range
/// - `consumer` (optional): Filter by specific consumer
///
/// # Response
/// Returns `String` - Simplified response (actual response structure is complex).
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XPending;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Get pending summary
/// let cmd = XPending::new("mystream", "mygroup");
/// let summary = client.call(cmd).await?;
///
/// // Get detailed list
/// let cmd = XPending::new("mystream", "mygroup")
///     .range("-", "+", 10);
/// let details = client.call(cmd).await?;
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XPending {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) start: Option<String>,
    pub(crate) end: Option<String>,
    pub(crate) count: Option<i64>,
    pub(crate) consumer: Option<String>,
}

impl XPending {
    /// Create a new XPENDING command
    pub fn new(key: impl Into<String>, group: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            start: None,
            end: None,
            count: None,
            consumer: None,
        }
    }

    /// Get detailed pending entries in range
    pub fn range(mut self, start: impl Into<String>, end: impl Into<String>, count: i64) -> Self {
        self.start = Some(start.into());
        self.end = Some(end.into());
        self.count = Some(count);
        self
    }

    /// Filter by specific consumer
    pub fn consumer(mut self, consumer: impl Into<String>) -> Self {
        self.consumer = Some(consumer.into());
        self
    }
}

impl Command for XPending {
    type Response = String; // Simplified - actual response is complex

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XPENDING"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
        ];

        if let (Some(start), Some(end), Some(count)) = (&self.start, &self.end, self.count) {
            args.push(Frame::BulkString(Some(Bytes::from(start.clone()))));
            args.push(Frame::BulkString(Some(Bytes::from(end.clone()))));
            args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));

            if let Some(consumer) = &self.consumer {
                args.push(Frame::BulkString(Some(Bytes::from(consumer.clone()))));
            }
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        // Simplified parsing - real implementation would be more complex
        Ok(format!("{:?}", frame))
    }
}

/// XCLAIM command - Changes the ownership of a pending message
///
/// In the context of a stream consumer group, this command changes the ownership of a pending message
/// so that the new owner is the consumer specified. This is useful when a consumer has crashed or
/// is taking too long to process messages.
///
/// # Request
/// - `key`: The stream key
/// - `group`: The consumer group name
/// - `consumer`: The consumer claiming the messages
/// - `min_idle_time`: Minimum idle time in milliseconds for messages to be claimable
/// - `ids`: One or more message IDs to claim
///
/// # Response
/// Returns `Vec<StreamEntry>` - The claimed messages.
///
/// # Redis Version
/// Available since Redis 5.0.0
///
/// # Examples
///
/// ```no_run
/// use redis_tower::commands::streams::XClaim;
/// use redis_tower::RedisClient;
///
/// # async fn example() -> Result<(), Box<dyn std::error::Error>> {
/// # let client = RedisClient::connect("127.0.0.1:6379").await?;
/// // Claim messages idle for more than 1 hour
/// let cmd = XClaim::new("mystream", "mygroup", "consumer2", 3600000)
///     .id("1526919030474-0");
/// let claimed = client.call(cmd).await?;
/// println!("Claimed {} messages", claimed.len());
/// # Ok(())
/// # }
/// ```
#[derive(Debug, Clone)]
pub struct XClaim {
    pub(crate) key: String,
    pub(crate) group: String,
    pub(crate) consumer: String,
    pub(crate) min_idle_time: i64,
    pub(crate) ids: Vec<String>,
}

impl XClaim {
    /// Create a new XCLAIM command
    pub fn new(
        key: impl Into<String>,
        group: impl Into<String>,
        consumer: impl Into<String>,
        min_idle_time: i64,
    ) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            consumer: consumer.into(),
            min_idle_time,
            ids: Vec::new(),
        }
    }

    /// Add an ID to claim
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.ids.push(id.into());
        self
    }
}

impl Command for XClaim {
    type Response = Vec<StreamEntry>;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XCLAIM"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
            Frame::BulkString(Some(Bytes::from(self.consumer.clone()))),
            Frame::BulkString(Some(Bytes::from(self.min_idle_time.to_string()))),
        ];

        for id in &self.ids {
            args.push(Frame::BulkString(Some(Bytes::from(id.clone()))));
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        parse_stream_entries(&frame)
    }
}

/// Stream entry with ID and field-value pairs
#[derive(Debug, Clone, PartialEq)]
pub struct StreamEntry {
    /// Entry ID (timestamp-sequence format)
    pub id: String,
    /// Field-value pairs in the entry
    pub fields: HashMap<String, String>,
}

/// Stream entries result (stream key + entries)
#[derive(Debug, Clone, PartialEq)]
pub struct StreamEntries {
    /// Stream key name
    pub key: String,
    /// Entries from the stream
    pub entries: Vec<StreamEntry>,
}

/// Helper to parse stream entries from a frame
fn parse_stream_entries(frame: &Frame) -> Result<Vec<StreamEntry>, RedisError> {
    match frame {
        Frame::Array(entries) => {
            let mut result = Vec::new();
            for entry in entries {
                if let Frame::Array(pair) = entry {
                    if pair.len() == 2 {
                        let id = match &pair[0] {
                            Frame::BulkString(Some(id)) => String::from_utf8_lossy(id).into_owned(),
                            _ => return Err(RedisError::UnexpectedResponse),
                        };

                        let fields = match &pair[1] {
                            Frame::Array(field_values) => {
                                let mut map = HashMap::new();
                                let mut i = 0;
                                while i < field_values.len() {
                                    if i + 1 < field_values.len() {
                                        let field = match &field_values[i] {
                                            Frame::BulkString(Some(f)) => {
                                                String::from_utf8_lossy(f).into_owned()
                                            }
                                            _ => return Err(RedisError::UnexpectedResponse),
                                        };
                                        let value = match &field_values[i + 1] {
                                            Frame::BulkString(Some(v)) => {
                                                String::from_utf8_lossy(v).into_owned()
                                            }
                                            _ => return Err(RedisError::UnexpectedResponse),
                                        };
                                        map.insert(field, value);
                                    }
                                    i += 2;
                                }
                                map
                            }
                            _ => return Err(RedisError::UnexpectedResponse),
                        };

                        result.push(StreamEntry { id, fields });
                    }
                }
            }
            Ok(result)
        }
        _ => Err(RedisError::UnexpectedResponse),
    }
}

/// Consumer information from XINFO CONSUMERS
#[derive(Debug, Clone, PartialEq)]
pub struct ConsumerInfo {
    /// Consumer name
    pub name: String,
    /// Number of pending messages
    pub pending: i64,
    /// Milliseconds since last attempted interaction
    pub idle: i64,
    /// Milliseconds since last successful interaction (Redis 7.2+)
    pub inactive: Option<i64>,
}

/// XINFO CONSUMERS command - Get information about consumers in a consumer group
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XInfoConsumers;
/// let cmd = XInfoConsumers::new("mystream", "mygroup");
/// ```
#[derive(Debug, Clone)]
pub struct XInfoConsumers {
    pub(crate) key: String,
    pub(crate) group: String,
}

impl XInfoConsumers {
    /// Create a new XINFO CONSUMERS command
    pub fn new(key: impl Into<String>, group: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
        }
    }
}

impl Command for XInfoConsumers {
    type Response = Vec<ConsumerInfo>;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XINFO"))),
            Frame::BulkString(Some(Bytes::from("CONSUMERS"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
            Frame::BulkString(Some(Bytes::from(self.group.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Array(items) => {
                let mut consumers = Vec::new();
                for item in items {
                    if let Frame::Array(fields) = item {
                        let mut name = String::new();
                        let mut pending = 0;
                        let mut idle = 0;
                        let mut inactive = None;

                        let mut i = 0;
                        while i < fields.len() {
                            if let Frame::BulkString(Some(key)) = &fields[i] {
                                let key_str = String::from_utf8_lossy(key);
                                if i + 1 < fields.len() {
                                    match key_str.as_ref() {
                                        "name" => {
                                            if let Frame::BulkString(Some(v)) = &fields[i + 1] {
                                                name = String::from_utf8_lossy(v).to_string();
                                            }
                                        }
                                        "pending" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                pending = v;
                                            }
                                        }
                                        "idle" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                idle = v;
                                            }
                                        }
                                        "inactive" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                inactive = Some(v);
                                            }
                                        }
                                        _ => {}
                                    }
                                }
                            }
                            i += 2;
                        }

                        consumers.push(ConsumerInfo {
                            name,
                            pending,
                            idle,
                            inactive,
                        });
                    }
                }
                Ok(consumers)
            }
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// Consumer group information from XINFO GROUPS
#[derive(Debug, Clone, PartialEq)]
pub struct GroupInfo {
    /// Group name
    pub name: String,
    /// Number of consumers in the group
    pub consumers: i64,
    /// Number of pending messages
    pub pending: i64,
    /// Last delivered ID
    pub last_delivered_id: String,
    /// Logical read counter (Redis 7.0+)
    pub entries_read: Option<i64>,
    /// Number of undelivered entries (Redis 7.0+)
    pub lag: Option<i64>,
}

/// XINFO GROUPS command - Get information about consumer groups for a stream
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XInfoGroups;
/// let cmd = XInfoGroups::new("mystream");
/// ```
#[derive(Debug, Clone)]
pub struct XInfoGroups {
    pub(crate) key: String,
}

impl XInfoGroups {
    /// Create a new XINFO GROUPS command
    pub fn new(key: impl Into<String>) -> Self {
        Self { key: key.into() }
    }
}

impl Command for XInfoGroups {
    type Response = Vec<GroupInfo>;

    fn to_frame(&self) -> Frame {
        Frame::Array(vec![
            Frame::BulkString(Some(Bytes::from("XINFO"))),
            Frame::BulkString(Some(Bytes::from("GROUPS"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ])
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Array(items) => {
                let mut groups = Vec::new();
                for item in items {
                    if let Frame::Array(fields) = item {
                        let mut name = String::new();
                        let mut consumers = 0;
                        let mut pending = 0;
                        let mut last_delivered_id = String::new();
                        let mut entries_read = None;
                        let mut lag = None;

                        let mut i = 0;
                        while i < fields.len() {
                            if let Frame::BulkString(Some(key)) = &fields[i] {
                                let key_str = String::from_utf8_lossy(key);
                                if i + 1 < fields.len() {
                                    match key_str.as_ref() {
                                        "name" => {
                                            if let Frame::BulkString(Some(v)) = &fields[i + 1] {
                                                name = String::from_utf8_lossy(v).to_string();
                                            }
                                        }
                                        "consumers" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                consumers = v;
                                            }
                                        }
                                        "pending" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                pending = v;
                                            }
                                        }
                                        "last-delivered-id" => {
                                            if let Frame::BulkString(Some(v)) = &fields[i + 1] {
                                                last_delivered_id =
                                                    String::from_utf8_lossy(v).to_string();
                                            }
                                        }
                                        "entries-read" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                entries_read = Some(v);
                                            }
                                        }
                                        "lag" => {
                                            if let Frame::Integer(v) = fields[i + 1] {
                                                lag = Some(v);
                                            }
                                        }
                                        _ => {}
                                    }
                                }
                            }
                            i += 2;
                        }

                        groups.push(GroupInfo {
                            name,
                            consumers,
                            pending,
                            last_delivered_id,
                            entries_read,
                            lag,
                        });
                    }
                }
                Ok(groups)
            }
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

/// Stream information from XINFO STREAM
#[derive(Debug, Clone, PartialEq)]
pub struct StreamInfo {
    /// Number of entries in the stream
    pub length: i64,
    /// Number of radix tree keys
    pub radix_tree_keys: i64,
    /// Number of radix tree nodes
    pub radix_tree_nodes: i64,
    /// Number of consumer groups
    pub groups: i64,
    /// Last generated ID
    pub last_generated_id: String,
    /// Maximum deleted entry ID
    pub max_deleted_entry_id: Option<String>,
    /// Total entries added during stream lifetime
    pub entries_added: Option<i64>,
    /// First entry (ID and fields)
    pub first_entry: Option<StreamEntry>,
    /// Last entry (ID and fields)
    pub last_entry: Option<StreamEntry>,
}

/// XINFO STREAM command - Get information about a stream
///
/// # Examples
///
/// ```rust,no_run
/// # use redis_tower::commands::streams::XInfoStream;
/// // Basic stream info
/// let cmd = XInfoStream::new("mystream");
///
/// // Full info with entries (Redis 6.0+)
/// let cmd = XInfoStream::new("mystream").full();
///
/// // Limit entries returned
/// let cmd = XInfoStream::new("mystream").full().count(100);
/// ```
#[derive(Debug, Clone)]
pub struct XInfoStream {
    pub(crate) key: String,
    pub(crate) full: bool,
    pub(crate) count: Option<i64>,
}

impl XInfoStream {
    /// Create a new XINFO STREAM command
    pub fn new(key: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            full: false,
            count: None,
        }
    }

    /// Request full information including entries (Redis 6.0+)
    pub fn full(mut self) -> Self {
        self.full = true;
        self
    }

    /// Limit the number of entries returned in full mode
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }
}

impl Command for XInfoStream {
    type Response = StreamInfo;

    fn to_frame(&self) -> Frame {
        let mut args = vec![
            Frame::BulkString(Some(Bytes::from("XINFO"))),
            Frame::BulkString(Some(Bytes::from("STREAM"))),
            Frame::BulkString(Some(Bytes::from(self.key.clone()))),
        ];

        if self.full {
            args.push(Frame::BulkString(Some(Bytes::from("FULL"))));
            if let Some(count) = self.count {
                args.push(Frame::BulkString(Some(Bytes::from("COUNT"))));
                args.push(Frame::BulkString(Some(Bytes::from(count.to_string()))));
            }
        }

        Frame::Array(args)
    }

    fn parse_response(frame: Frame) -> Result<Self::Response, RedisError> {
        match frame {
            Frame::Array(fields) => {
                let mut length = 0;
                let mut radix_tree_keys = 0;
                let mut radix_tree_nodes = 0;
                let mut groups = 0;
                let mut last_generated_id = String::new();
                let mut max_deleted_entry_id = None;
                let mut entries_added = None;
                let mut first_entry = None;
                let mut last_entry = None;

                let mut i = 0;
                while i < fields.len() {
                    if let Frame::BulkString(Some(key)) = &fields[i] {
                        let key_str = String::from_utf8_lossy(key);
                        if i + 1 < fields.len() {
                            match key_str.as_ref() {
                                "length" => {
                                    if let Frame::Integer(v) = fields[i + 1] {
                                        length = v;
                                    }
                                }
                                "radix-tree-keys" => {
                                    if let Frame::Integer(v) = fields[i + 1] {
                                        radix_tree_keys = v;
                                    }
                                }
                                "radix-tree-nodes" => {
                                    if let Frame::Integer(v) = fields[i + 1] {
                                        radix_tree_nodes = v;
                                    }
                                }
                                "groups" => {
                                    if let Frame::Integer(v) = fields[i + 1] {
                                        groups = v;
                                    }
                                }
                                "last-generated-id" => {
                                    if let Frame::BulkString(Some(v)) = &fields[i + 1] {
                                        last_generated_id = String::from_utf8_lossy(v).to_string();
                                    }
                                }
                                "max-deleted-entry-id" => {
                                    if let Frame::BulkString(Some(v)) = &fields[i + 1] {
                                        max_deleted_entry_id =
                                            Some(String::from_utf8_lossy(v).to_string());
                                    }
                                }
                                "entries-added" => {
                                    if let Frame::Integer(v) = fields[i + 1] {
                                        entries_added = Some(v);
                                    }
                                }
                                "first-entry" => {
                                    if let Frame::Array(entry_fields) = &fields[i + 1] {
                                        if entry_fields.len() >= 2 {
                                            if let (
                                                Frame::BulkString(Some(id)),
                                                Frame::Array(field_pairs),
                                            ) = (&entry_fields[0], &entry_fields[1])
                                            {
                                                let mut entry_map = HashMap::new();
                                                for j in (0..field_pairs.len()).step_by(2) {
                                                    if j + 1 < field_pairs.len() {
                                                        if let (
                                                            Frame::BulkString(Some(k)),
                                                            Frame::BulkString(Some(v)),
                                                        ) =
                                                            (&field_pairs[j], &field_pairs[j + 1])
                                                        {
                                                            entry_map.insert(
                                                                String::from_utf8_lossy(k)
                                                                    .to_string(),
                                                                String::from_utf8_lossy(v)
                                                                    .to_string(),
                                                            );
                                                        }
                                                    }
                                                }
                                                first_entry = Some(StreamEntry {
                                                    id: String::from_utf8_lossy(id).to_string(),
                                                    fields: entry_map,
                                                });
                                            }
                                        }
                                    }
                                }
                                "last-entry" => {
                                    if let Frame::Array(entry_fields) = &fields[i + 1] {
                                        if entry_fields.len() >= 2 {
                                            if let (
                                                Frame::BulkString(Some(id)),
                                                Frame::Array(field_pairs),
                                            ) = (&entry_fields[0], &entry_fields[1])
                                            {
                                                let mut entry_map = HashMap::new();
                                                for j in (0..field_pairs.len()).step_by(2) {
                                                    if j + 1 < field_pairs.len() {
                                                        if let (
                                                            Frame::BulkString(Some(k)),
                                                            Frame::BulkString(Some(v)),
                                                        ) =
                                                            (&field_pairs[j], &field_pairs[j + 1])
                                                        {
                                                            entry_map.insert(
                                                                String::from_utf8_lossy(k)
                                                                    .to_string(),
                                                                String::from_utf8_lossy(v)
                                                                    .to_string(),
                                                            );
                                                        }
                                                    }
                                                }
                                                last_entry = Some(StreamEntry {
                                                    id: String::from_utf8_lossy(id).to_string(),
                                                    fields: entry_map,
                                                });
                                            }
                                        }
                                    }
                                }
                                _ => {}
                            }
                        }
                    }
                    i += 2;
                }

                Ok(StreamInfo {
                    length,
                    radix_tree_keys,
                    radix_tree_nodes,
                    groups,
                    last_generated_id,
                    max_deleted_entry_id,
                    entries_added,
                    first_entry,
                    last_entry,
                })
            }
            Frame::Error(e) => Err(RedisError::from_redis_error(&String::from_utf8_lossy(&e))),
            _ => Err(RedisError::UnexpectedResponse),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xadd_frame() {
        let cmd = XAdd::new("mystream")
            .field("temp", "25.5")
            .field("humidity", "60");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XADD"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("mystream"))));
            assert_eq!(items[2], Frame::BulkString(Some(Bytes::from("*"))));
            assert_eq!(items[3], Frame::BulkString(Some(Bytes::from("temp"))));
            assert_eq!(items[4], Frame::BulkString(Some(Bytes::from("25.5"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xadd_with_maxlen_frame() {
        let cmd = XAdd::new("mystream").maxlen(1000).field("x", "y");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("MAXLEN"))))
            );
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("~"))))
            );
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xread_frame() {
        let cmd = XRead::new().stream("s1", "0-0").stream("s2", "$");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XREAD"))));
            // Should have STREAMS keyword
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("STREAMS"))))
            );
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xrange_frame() {
        let cmd = XRange::new("mystream", "-", "+").count(10);

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XRANGE"))));
            assert_eq!(items[2], Frame::BulkString(Some(Bytes::from("-"))));
            assert_eq!(items[3], Frame::BulkString(Some(Bytes::from("+"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xlen_frame() {
        let cmd = XLen::new("mystream");
        let frame = cmd.to_frame();

        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 2);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XLEN"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xgroup_create_frame() {
        let cmd = XGroupCreate::new("stream", "group", "$").mkstream();

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XGROUP"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("CREATE"))));
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("MKSTREAM"))))
            );
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xgroup_createconsumer_frame() {
        let cmd = XGroupCreateConsumer::new("stream", "group", "consumer1");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 5);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XGROUP"))));
            assert_eq!(
                items[1],
                Frame::BulkString(Some(Bytes::from("CREATECONSUMER")))
            );
            assert_eq!(items[2], Frame::BulkString(Some(Bytes::from("stream"))));
            assert_eq!(items[3], Frame::BulkString(Some(Bytes::from("group"))));
            assert_eq!(items[4], Frame::BulkString(Some(Bytes::from("consumer1"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xgroup_delconsumer_frame() {
        let cmd = XGroupDelConsumer::new("stream", "group", "consumer1");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 5);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XGROUP"))));
            assert_eq!(
                items[1],
                Frame::BulkString(Some(Bytes::from("DELCONSUMER")))
            );
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xgroup_setid_frame() {
        let cmd = XGroupSetId::new("stream", "group", "$");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XGROUP"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("SETID"))));
            assert_eq!(items[4], Frame::BulkString(Some(Bytes::from("$"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xgroup_setid_with_entries_read() {
        let cmd = XGroupSetId::new("stream", "group", "1234-0").entries_read(1000);

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 7);
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("ENTRIESREAD"))))
            );
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("1000"))))
            );
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xinfo_consumers_frame() {
        let cmd = XInfoConsumers::new("stream", "group");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 4);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XINFO"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("CONSUMERS"))));
            assert_eq!(items[2], Frame::BulkString(Some(Bytes::from("stream"))));
            assert_eq!(items[3], Frame::BulkString(Some(Bytes::from("group"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xinfo_groups_frame() {
        let cmd = XInfoGroups::new("stream");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 3);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XINFO"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("GROUPS"))));
            assert_eq!(items[2], Frame::BulkString(Some(Bytes::from("stream"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xinfo_stream_frame() {
        let cmd = XInfoStream::new("stream");

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert_eq!(items.len(), 3);
            assert_eq!(items[0], Frame::BulkString(Some(Bytes::from("XINFO"))));
            assert_eq!(items[1], Frame::BulkString(Some(Bytes::from("STREAM"))));
        } else {
            panic!("Expected Array frame");
        }
    }

    #[test]
    fn test_xinfo_stream_full() {
        let cmd = XInfoStream::new("stream").full().count(100);

        let frame = cmd.to_frame();
        if let Frame::Array(items) = frame {
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("FULL"))))
            );
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("COUNT"))))
            );
            assert!(
                items
                    .iter()
                    .any(|f| f == &Frame::BulkString(Some(Bytes::from("100"))))
            );
        } else {
            panic!("Expected Array frame");
        }
    }
}

/// XGROUP HELP command - Get help text for XGROUP subcommands
///
/// Available since Redis 5.0.0.
#[derive(Debug, Clone, Copy)]
pub struct XGroupHelp;

impl XGroupHelp {
    pub fn new() -> Self {
        Self
    }
}

impl Default for XGroupHelp {
    fn default() -> Self {
        Self::new()
    }
}

impl crate::commands::Command for XGroupHelp {
    type Response = Vec<String>;

    fn to_frame(&self) -> crate::codec::Frame {
        crate::codec::Frame::Array(vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XGROUP"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("HELP"))),
        ])
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::Array(items) => Ok(items
                .into_iter()
                .filter_map(|item| match item {
                    crate::codec::Frame::BulkString(Some(data)) => {
                        Some(String::from_utf8_lossy(&data).to_string())
                    }
                    _ => None,
                })
                .collect()),
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}

/// XINFO HELP command - Get help text for XINFO subcommands
///
/// Available since Redis 5.0.0.
#[derive(Debug, Clone, Copy)]
pub struct XInfoHelp;

impl XInfoHelp {
    pub fn new() -> Self {
        Self
    }
}

impl Default for XInfoHelp {
    fn default() -> Self {
        Self::new()
    }
}

impl crate::commands::Command for XInfoHelp {
    type Response = Vec<String>;

    fn to_frame(&self) -> crate::codec::Frame {
        crate::codec::Frame::Array(vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XINFO"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("HELP"))),
        ])
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::Array(items) => Ok(items
                .into_iter()
                .filter_map(|item| match item {
                    crate::codec::Frame::BulkString(Some(data)) => {
                        Some(String::from_utf8_lossy(&data).to_string())
                    }
                    _ => None,
                })
                .collect()),
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}

/// XAUTOCLAIM command - Automatic claim of pending messages (Redis 6.2+)
///
/// Claims pending messages that have been idle for a given time and assigns them to a consumer.
///
/// Available since Redis 6.2.0.
#[derive(Debug, Clone)]
pub struct XAutoClaim {
    key: String,
    group: String,
    consumer: String,
    min_idle_time: i64,
    start: String,
    count: Option<i64>,
}

impl XAutoClaim {
    /// Create a new XAUTOCLAIM command
    pub fn new(
        key: impl Into<String>,
        group: impl Into<String>,
        consumer: impl Into<String>,
        min_idle_time: i64,
        start: impl Into<String>,
    ) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            consumer: consumer.into(),
            min_idle_time,
            start: start.into(),
            count: None,
        }
    }

    /// Set maximum number of messages to claim
    pub fn count(mut self, count: i64) -> Self {
        self.count = Some(count);
        self
    }
}

impl crate::commands::Command for XAutoClaim {
    type Response = (String, Vec<StreamEntry>);

    fn to_frame(&self) -> crate::codec::Frame {
        let mut frames = vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XAUTOCLAIM"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.key.clone()))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.group.clone()))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.consumer.clone()))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(
                self.min_idle_time.to_string(),
            ))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.start.clone()))),
        ];
        if let Some(count) = self.count {
            frames.push(crate::codec::Frame::BulkString(Some(bytes::Bytes::from(
                "COUNT",
            ))));
            frames.push(crate::codec::Frame::BulkString(Some(bytes::Bytes::from(
                count.to_string(),
            ))));
        }
        crate::codec::Frame::Array(frames)
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::Array(items) if items.len() >= 2 => {
                let next_id = match &items[0] {
                    crate::codec::Frame::BulkString(Some(data)) => {
                        String::from_utf8_lossy(data).to_string()
                    }
                    _ => return Err(crate::types::RedisError::UnexpectedResponse),
                };
                Ok((next_id, vec![]))
            }
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}

/// XACK command variant that also deletes acknowledged messages
/// Note: This is not a standard Redis command - included for completeness
#[derive(Debug, Clone)]
pub struct XAckDel {
    key: String,
    group: String,
    ids: Vec<String>,
}

impl XAckDel {
    /// Create a new XACKDEL command
    pub fn new(
        key: impl Into<String>,
        group: impl Into<String>,
        ids: Vec<impl Into<String>>,
    ) -> Self {
        Self {
            key: key.into(),
            group: group.into(),
            ids: ids.into_iter().map(|id| id.into()).collect(),
        }
    }
}

impl crate::commands::Command for XAckDel {
    type Response = i64;

    fn to_frame(&self) -> crate::codec::Frame {
        let mut frames = vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XACKDEL"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.key.clone()))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.group.clone()))),
        ];
        for id in &self.ids {
            frames.push(crate::codec::Frame::BulkString(Some(bytes::Bytes::from(
                id.clone(),
            ))));
        }
        crate::codec::Frame::Array(frames)
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::Integer(n) => Ok(n),
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}

/// XDEL variant with extended functionality
/// Note: This is not a standard Redis command - included for completeness
#[derive(Debug, Clone)]
pub struct XDelEx {
    key: String,
    ids: Vec<String>,
}

impl XDelEx {
    /// Create a new XDELEX command
    pub fn new(key: impl Into<String>, ids: Vec<impl Into<String>>) -> Self {
        Self {
            key: key.into(),
            ids: ids.into_iter().map(|id| id.into()).collect(),
        }
    }
}

impl crate::commands::Command for XDelEx {
    type Response = i64;

    fn to_frame(&self) -> crate::codec::Frame {
        let mut frames = vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XDELEX"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.key.clone()))),
        ];
        for id in &self.ids {
            frames.push(crate::codec::Frame::BulkString(Some(bytes::Bytes::from(
                id.clone(),
            ))));
        }
        crate::codec::Frame::Array(frames)
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::Integer(n) => Ok(n),
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}

/// XSETID command - Set the last delivered ID for a stream (Redis 7.0+)
///
/// Sets the last delivered ID for a stream.
///
/// Available since Redis 7.0.0.
#[derive(Debug, Clone)]
pub struct XSetId {
    key: String,
    id: String,
}

impl XSetId {
    /// Create a new XSETID command
    pub fn new(key: impl Into<String>, id: impl Into<String>) -> Self {
        Self {
            key: key.into(),
            id: id.into(),
        }
    }
}

impl crate::commands::Command for XSetId {
    type Response = ();

    fn to_frame(&self) -> crate::codec::Frame {
        crate::codec::Frame::Array(vec![
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from("XSETID"))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.key.clone()))),
            crate::codec::Frame::BulkString(Some(bytes::Bytes::from(self.id.clone()))),
        ])
    }

    fn parse_response(
        frame: crate::codec::Frame,
    ) -> Result<Self::Response, crate::types::RedisError> {
        match frame {
            crate::codec::Frame::SimpleString(_) => Ok(()),
            crate::codec::Frame::Error(e) => Err(crate::types::RedisError::from_redis_error(
                &String::from_utf8_lossy(&e),
            )),
            _ => Err(crate::types::RedisError::UnexpectedResponse),
        }
    }
}
